/* autogenerated by Processing revision 1283 on 2022-04-28 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class sketch_220427b extends PApplet {

boolean[][] pixels;
int pxSize = 5;
int stillFrameRate = 120;
int FrameRate = 30;
boolean run = false;
boolean setTo = true;

public boolean inScreen() {
  return mouseX >= 0 && mouseY >= 0 && mouseX < width && mouseY < height;
}

 public void setup() {
  /* size commented out by preprocessor */;

  pixels = new boolean[width / pxSize][height / pxSize];

  background(0);
  frameRate(stillFrameRate);
  fill(255);
}

 public void mousePressed() {
  if (mousePressed && inScreen())
    setTo = !pixels[mouseX / pxSize][mouseY / pxSize];
}

 public void keyPressed() {
  if (key == 's') {
    run ^= true;
    if (run)
      frameRate(FrameRate);
    else
      frameRate(stillFrameRate);
  } else if (key == 'r') {
    for (int x = 1; x < pixels.length - 1; x++)
      for (int y = 1; y < pixels[x].length - 1; y++)
        pixels[x][y] = run = false;
  }
}

 public void mouseWheel(MouseEvent event) {
  FrameRate -= event.getCount();
  if (FrameRate < 0)
    FrameRate = 1;
  // System.out.println(FrameRate);
  frameRate(FrameRate);
}

 public void draw() {
  background(0);

  if (mousePressed && inScreen())
    pixels[mouseX / pxSize][mouseY / pxSize] = setTo;

  boolean[][] newPixels = new boolean[pixels.length][pixels[0].length];
  for (int x = 0; x < pixels.length - 0; x++)
    for (int y = 0; y < pixels[0].length - 0; y++)
      newPixels[x][y] = !!pixels[x][y];

  if (run)
    for (int x = 1; x < pixels.length - 1; x++)
      for (int y = 1; y < pixels[x].length - 1; y++) {
        boolean[] neighbours = {
          pixels[x - 1][y + 1],
          pixels[x][y + 1],
          pixels[x + 1][y + 1],
          pixels[x - 1][y],
          pixels[x + 1][y],
          pixels[x - 1][y - 1],
          pixels[x][y - 1],
          pixels[x + 1][y - 1]
        };
        int alive = 0;
        for (int i = 0; i < 8; i++)
          if (neighbours[i])
            alive++;

        newPixels[x][y] =
          (pixels[x][y] && (alive == 2 || alive == 3)) ||
          (!pixels[x][y] && alive == 3);
      }

  pixels = newPixels;

  for (int x = 0; x < pixels.length; x++)
    for (int y = 0; y < pixels[0].length; y++)
      if (pixels[x][y])
        square(x * pxSize, y * pxSize, pxSize);
}


  public void settings() { fullScreen(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "sketch_220427b" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
